version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    networks:
      - webnet
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet:
